### ISSUE TITLE
What's broken as of 18 September 2020

### ISSUE THREAD

**Issue by koltoast** [justinikeako/darklingo#1]
https://www.duolingo.com/stories is broken when the selected language course is not among the languages with stories
https://blog.duolingo.com/ and https://incubator.duolingo.com/ aswell

**Comment by justinikeako** [comment]
Looking into it currently... should be an update by Saturday at latest.

**Comment by justinikeako** [comment]
Done! However, since I'm not a contributor, I could only make changes to a few pages rather than the whole incubator subdomain.
