### ISSUE TITLE
Profile icon not showing when window resized to mobile size

### ISSUE THREAD

**Issue by lupomikti** [justinikeako/darklingo#3]
When changing the size of the window to a width that positions the elements as if on a mobile browser, the navigation icons move to the bottom of the window. One of the icons, the Profile icon, appears to be missing but is in fact there and just having its color set the same as the background somehow.

The `<li>` element has html as follows:
```html
<li class="_2AHxr">
    <a class="TkgeC _1cNmN" data-test="profile-tab" href="https://www.duolingo.com/profile/LupoMikti">
        <span class="">
            <img class="_1avU-" src="//duolingo-forum-web.duolingo.com/web-ui/images/icons/34684767e8a869415794c37d3c62a0be.svg">
        </span>
    </a>
</li>
```

Here is a picture showing the issue with both the theme activated and deactivated and a red box to highlight the issue:
![missing_icon_example](https://user-images.githubusercontent.com/25500382/94478566-4a614200-0188-11eb-902e-ac06a216fd5d.png)

**Comment by justinikeako** [comment]
Working on it!

**Comment by justinikeako** [comment]
Fixed!
