### ISSUE TITLE
Some styles don't work

### ISSUE THREAD

**Issue by taffarel55** [justinikeako/darklingo#6]
Hello, I noticed that some styles on the page have not been working very well, below is an example:

![image](https://user-images.githubusercontent.com/18634201/112975709-5c697080-912a-11eb-9877-f200e374fff9.png)

**Comment by justinikeako** [comment]
Sorry for leaving this for so long! Fixed this issue a while ago. All should be good.

**Comment by taffarel55** [comment]
Yes I see!! Thanks <3
