### ISSUE TITLE
Special characters are not styled

### ISSUE THREAD

**Issue by denizevrenci** [justinikeako/darklingo#7]
![image](https://user-images.githubusercontent.com/6046851/136705514-260be877-2154-4c1a-9fbf-a50e013ba73b.png)

**Comment by justinikeako** [comment]
Just fixed this issue today! Feel free to tell me if you find any other problems with it though.

**Comment by denizevrenci** [comment]
Looks great! Thank you.
![image](https://user-images.githubusercontent.com/6046851/140839668-d7035fb0-1e83-4079-b6be-7c5b6b6ae3cb.png)
